#
# Kiosk messages
#

# start_message.cc
{100}{}{РЕЖИМ КИОСКА}
{101}{}{Осторожно: вызывает привыкание}
{200}{}{Вносит изменения в игру,}
{201}{}{а именно:}
{202}{}{- Недоступны сохранение}
{203}{}{  и загрузка игры}
{204}{}{- Предустановлены опции и}
{205}{}{  недоступно данное меню}
{206}{}{- Персонаж начинает}
{207}{}{  с уровнем}
{208}{}{- После создания персонажа,}
{209}{}{  предлaгается выбор}
{210}{}{  стартового инвентаря}
{400}{}{Если Вы считаете что,}
{401}{}{достаточно знакомы с игрой,}
{402}{}{переключите на сложно}
{403}{}{В случае если,}
{404}{}{Вы - несовершеннолетний,}
{405}{}{беременная женщина,}
{406}{}{кормящая мать или}
{407}{}{просто достаточно нежны,}
{408}{}{включите фильтр речи!}
{409}{}{П.С. Вас предупреждали}
{500}{}{Текущие настройки}
{501}{}{Сложность игры:}
{502}{}{- %s}
{503}{}{Сложность в бою:}
{504}{}{- %s}
{505}{}{Фильтр речи:}
{506}{}{- %s}
{999}{}{(Игра закончится через %d секунд)}
{1000}{}{Ку-ку, не уснул там?}
{1001}{}{Не спи, замерзнешь!}
{1002}{}{Заплатил налоги - спишь спокойно}
{1003}{}{Минуточку внимания, вообще-то, я здесь!}
{1004}{}{Заскучал без тебя}
{1005}{}{Пишите письма...}
{1006}{}{Ну где ты там?!}
{1007}{}{Не могу так больше..}
{1008}{}{Хочу внимания! И ментатов}
{1009}{}{Мастера не убил, а уже свалил куда-то}
{1010}{}{Убежище без тебя погибнет!}
{1011}{}{Так дерево у Гарольда не прорастет}
{1012}{}{Будь Ричарт Мороу как ты, ничего не случилось бы}
{1013}{}{Тим Кейн передает привет!}
{1014}{}{Поиграй в игру, пожалуйста}
{1015}{}{У "Фаргуса" перевод - лучший}
{1016}{}{Мы - здесь, а ты?}
{1017}{}{Удели мне время}
{1018}{}{Я бы сказал, но промолчу}
{1019}{}{Тук-тук, есть кто?}
{1020}{}{С этой стороны экрана тишина, как с твоей?}
{1050}{}{Время убегает!}
{1051}{}{Ой ёй, совсем мало осталось}
{1052}{}{П-А-М-А-Г-И-Т-Е}
{1053}{}{Часики тикают. Тик-так. Тик-так}
{1054}{}{Хоть рад-скорпионов в пещере убил?}
{1055}{}{Мог бы в Свечение сходить}
{1056}{}{Укради деталь у Ромбуса}
{1057}{}{Знаешь сколько веревок на всю игру?}
{1058}{}{А сколько шариков для воздушки?}
{1059}{}{Выходец - мой дед, - Старейшина}
{1060}{}{Поспеши!}
{1061}{}{Игра не волк, в лес не убежит}
{1062}{}{Если подождешь еще, увидишь новое сообщение}
{1063}{}{Время не ждет!}
{1064}{}{Спасать убежище, собираешься?}
{1065}{}{Ты еще не всех убил}
{1066}{}{Зубы не всем заговорил, возвращайся!}
{1067}{}{Просто... не бросай меня}
{1068}{}{Вернись в игру}
{1069}{}{Пощелкай мышкой, желательно осмыслено}
{1070}{}{Здесь должно быть очень язвительное сообщение}
{1100}{}{Знаешь который час? Час смерти}
{1101}{}{Опять ты бросил меня на погибель}
{1102}{}{Вот так Мастер и создал высшую расу}
{1103}{}{Эх, кончился Выходец}
{1104}{}{Часики оттикали}
{1105}{}{Я бы застрелился, но функционал не завезли}
{1105}{}{Лучше бы в чан макнули}
{1107}{}{ДА СДЕЛАЙ УЖЕ ЧТО-НИБУДЬ!}
{1108}{}{Спаси мир, обезвредь бомбу за секунду до..}
{1109}{}{Вы критически ранены в пах, и теряете сознание}
{1110}{}{Еще чуть-чуть, еще немного..}
{1111}{}{Все там будем}
{1112}{}{В убежище трупы сжигают}
{1113}{}{Смотритель еще кого-то отправит}
{1114}{}{Знаешь где чип?! Я знаю! Но не скажу}
{1115}{}{Я хотел бы птицей стать и свободно летать}
{1116}{}{Подожди еще немного, и начни сначала}
{1117}{}{Конец близок!}
{1118}{}{Вы выбросили "1"}
{1119}{}{10-9-8-7... Ах, какая кому разница?}
{1120}{}{А мог просто нажать "выйти"}
