#
# Kiosk messages
#

# start_message.cc
{100}{}{РЕЖИМ КИОСКА}
{101}{}{Осторожно: вызывает привыкание}
{200}{}{Вносит изменения в игру,}
{201}{}{а именно:}
{202}{}{- Недоступны сохранение}
{203}{}{  и загрузка игры}
{204}{}{- Предустановлены опции и}
{205}{}{  недоступно данное меню}
{206}{}{- Персонаж начинает}
{207}{}{  с уровнем}
{208}{}{- После создания персонажа,}
{209}{}{  предлогается выбор}
{210}{}{  стартового инвентаря}
{400}{}{Если Вы считаете что,}
{401}{}{достаточно знакомы с игрой,}
{402}{}{переключите на сложно}
{403}{}{В случае если,}
{404}{}{Вы - несовершеннолетний,}
{405}{}{беременная женщина,}
{406}{}{кормящая мать или}
{407}{}{просто достаточно нежны,}
{408}{}{включите фильтр речи!}
{409}{}{П.С. Вас предупреждали}
{500}{}{Текущие настройки}
{501}{}{Сложность игры:}
{502}{}{- %s}
{503}{}{Сложность в бою:}
{504}{}{- %s}
{505}{}{Фильтр речи:}
{506}{}{- %s}
